# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PoyntSDKExampleApp' do

  use_frameworks!
  #pod 'PoyntLib', :git => 'https://github.com/mcconkiee/poyntsdk.git', :branch => 'bugsnagg'
  pod 'PoyntLib', :path => '../'
end
